server.port=8080

spring.data.redis.host=localhost
spring.data.redis.port=6379

ratelimiter.strategy=DOMAIN
ratelimiter.algorithm=SLIDING_WINDOW
ratelimiter.redis.key-prefix=rl
ratelimiter.analytics.enabled=false

logging.pattern.console=%d{HH:mm:ss.SSS} %-5level [%X{correlationId}] %logger{36} - %msg%n

spring.autoconfigure.exclude=org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.jdbc.autoconfigure.DataSourceInitializationAutoConfiguration